name: Create Release Branch

on: 
  workflow_dispatch:
  schedule:
  # every friday at AM11:00
    - cron: '0 2 * * 5'

jobs:
  create_release_branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: develop
          fetch-depth: 0
      - name: Setup git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email noreply@github.com
      - name: Get current version
        id: get_cur_ver
        run: |
          ver=`git tag --sort=-v:refname | head -n 1`
          echo "::set-output name=version::${ver#v}"
      - name: Bump version
        id: bump_version
        uses: christian-draeger/increment-semantic-version@1.0.2
        with:
          current-version: ${{ steps.get_cur_ver.outputs.version }}
          version-fragment: 'feature'
      - name: Create Release Branch
        run: |
          release_branch=release/v${{ steps.bump_version.outputs.next-version }}
          git checkout -b ${release_branch}
          git push origin ${release_branch}
      - name: Create History
        id: create_history
        run: |
          release_branch=release/v${{ steps.bump_version.outputs.next-version }}
          git checkout -b main origin/main
          cmd="git log --merges --pretty=format:'%s (@%an)' --date=relative \"main...${release_branch}\""
          log=`eval ${cmd}`
          echo "::set-output name=cmd::${cmd}"
          echo "::set-output name=log::${log}"
      - name: Create Pull Request
        run: |
          release_branch=release/v${{ steps.bump_version.outputs.next-version }}
          hub pull-request \
              --base main \
              --head ${release_branch} \
              --reviewer guppy-brown \
              --assign guppy-brown \
              --labels ":rocket: release" \
              --message "Release/${{ steps.bump_version.outputs.next-version }}" \
              --message "## Executed command" \
              --message "\`${{ steps.create_history.outputs.cmd }}\`" \
              --message "## Command result" \
              --message "${{ steps.create_history.outputs.log }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

