name: Create Release Branch

on: 
  workflow_dispatch:
  schedule:
  # every friday at AM11:00
    - cron: '0 2 * * 5'

jobs:
  create_release_branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: develop
          fetch-depth: 0
