name: Create Release Branch

on: 
  workflow_dispatch:
  schedule:
  # every friday at AM11:00
    - cron: '0 2 * * 5'

jobs:
  create_release_branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: develop
          fetch-depth: 0
      - name: Get current version
        id: get_cur_ver
        run: |
          ver = git tag --sort=-v:refname | head -n 1 | cut -f 1 -d v
          echo "::set-output name=version::${ver}"
      - name: Bump version
        id: bunp_version
        uses: christian-draeger/increment-semantic-version@1.0.2
        with:
          current-version: ${{ steps.get_cur_ver.version }}
          version-fragment: 'feature'
      - name: dump next version(for confirm)
        run: |
          echo ${{ steps.bump_version.outputs.next-version }}
